apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helloworld-chart.fullname" . }}
spec:
  path: /
  to:
    kind: Service
    name: {{ include "helloworld-chart.fullname" . }}
  port:
    targetPort: 8080