apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-tcp
spec:
  containers:
  - name: helloword-chart-helloworld-chart-6576b7bf79-95t48 
    image: quay.io/bszeti/fuse7hello:latest
    ports:
    - containerPort: 8080 
    livenessProbe:  
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15 
      timeoutSeconds: 1  
