apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
  - args:
    image: quay.io/bszeti/fuse7hello:latest
    name: helloword-chart-helloworld-chart-6576b7bf79-95t48
    readinessProbe:  
    httpGet:
    # host: my-host 
    # scheme: HTTPS 
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 15  
    timeoutSeconds: 1  
